#!/usr/bin/env python3
"""
Скрип для триангуляции OBJ файла (разбияние квадов на треугольники)
и масштабирования модели
"""

import sys

def triangulate_and_scale_obj(input_file, output_file, scale=0.1):
    """
    Читает OBJ файл, триангулирует все четырехугольники и масштабирует модель
    """
    vertices = []
    normals = []
    texcoords = []
    faces = []
    
    # Читаем оригинальный файл
    with open(input_file, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            parts = line.split()
            if not parts:
                continue
                
            if parts[0] == 'v':
                # Масштабируем вершины
                x, y, z = float(parts[1]) * scale, float(parts[2]) * scale, float(parts[3]) * scale
                vertices.append(f"v {x} {y} {z}")
            elif parts[0] == 'vn':
                normals.append(f"vn {parts[1]} {parts[2]} {parts[3]}")
            elif parts[0] == 'vt':
                texcoords.append(f"vt {parts[1]} {parts[2]}")
            elif parts[0] == 'f':
                # Триангулируем грани (поддерживаем и треугольники и квады)
                face_parts = parts[1:]
                
                if len(face_parts) == 3:
                    # Это уже треугольник
                    faces.append(f"f {face_parts[0]} {face_parts[1]} {face_parts[2]}")
                elif len(face_parts) == 4:
                    # Это четырёхугольник, разбиваем на два треугольника
                    # Треугольник 1: v0, v1, v2
                    faces.append(f"f {face_parts[0]} {face_parts[1]} {face_parts[2]}")
                    # Треугольник 2: v0, v2, v3
                    faces.append(f"f {face_parts[0]} {face_parts[2]} {face_parts[3]}")
                else:
                    print(f"Неподдерживаемая грань с {len(face_parts)} вершинами: {line}", file=sys.stderr)
    
    # Пишем новый файл
    with open(output_file, 'w') as f:
        f.write("# Triangulated OBJ file\n")
        f.write("# Generated by triangulate.py\n\n")
        
        if vertices:
            f.write("# Vertices\n")
            f.writelines([v + "\n" for v in vertices])
        
        if texcoords:
            f.write("\n# Texture coordinates\n")
            f.writelines([t + "\n" for t in texcoords])
        
        if normals:
            f.write("\n# Normals\n")
            f.writelines([n + "\n" for n in normals])
        
        if faces:
            f.write("\n# Faces\n")
            f.writelines([face + "\n" for face in faces])
    
    print(f"Vertices: {len(vertices)}")
    print(f"Texcoords: {len(texcoords)}")
    print(f"Normals: {len(normals)}")
    print(f"Faces: {len(faces)}")
    print(f"Processed: {input_file} -> {output_file}")

if __name__ == "__main__":
    input_file = "/home/gamesir/АГС/lab5/example/MESHES/cat/12221_Cat_v1_l3.obj"
    output_file = "/home/gamesir/АГС/lab5/example/MESHES/cat/12221_Cat_v1_l3_tri.obj"
    scale = 0.08  # Масштабируем на 0.08
    
    triangulate_and_scale_obj(input_file, output_file, scale)
